version: "3.3"

services:
  mongo:
    image: mongo
    container_name: mongo-broker-backend
    environment:
      MONGODB_DATABASE: broker
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
